"""Add description field

Revision ID: 42d3400175b3
Revises: 5e2ef12760a4
Create Date: 2017-02-24 14:31:48.263104

"""

# revision identifiers, used by Alembic.
revision = '42d3400175b3'
down_revision = '5e2ef12760a4'

from alembic import op
import sqlalchemy as sa
import oh_queue.models
from oh_queue.models import *


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'description')
    # ### end Alembic commands ###
