"""empty message

Revision ID: 03b92dc59571
Revises: e4b5bd2a05cc
Create Date: 2020-02-23 03:16:53.894778

"""

# revision identifiers, used by Alembic.
revision = '03b92dc59571'
down_revision = 'e4b5bd2a05cc'

from alembic import op
import sqlalchemy as sa
import oh_queue.models
from oh_queue.models import *


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('juggle_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'juggle_time')
    # ### end Alembic commands ###
