"""added appointment description field

Revision ID: 3b7d60ea61e3
Revises: 1f54dee7ae76
Create Date: 2020-04-05 08:30:54.515681

"""

# revision identifiers, used by Alembic.
revision = '3b7d60ea61e3'
down_revision = '1f54dee7ae76'

from alembic import op
import sqlalchemy as sa
import oh_queue.models
from oh_queue.models import *


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('description', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment', 'description')
    # ### end Alembic commands ###
