"""Add models for HW party mode

Revision ID: 4c81c3744bc4
Revises: e80617a584e0
Create Date: 2020-07-05 06:22:08.392455

"""

# revision identifiers, used by Alembic.
from sqlalchemy import orm

revision = '4c81c3744bc4'
down_revision = 'e80617a584e0'

from alembic import op
import sqlalchemy as sa
import oh_queue.models
from oh_queue.models import *


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('group_status', oh_queue.models.db.String(length=255), nullable=False),
    sa.Column('call_url', sa.String(length=255), nullable=True),
    sa.Column('doc_url', sa.String(length=255), nullable=True),
    sa.Column('course', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_assignment_id'), 'group', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_group_course'), 'group', ['course'], unique=False)
    op.create_index(op.f('ix_group_created'), 'group', ['created'], unique=False)
    op.create_index(op.f('ix_group_location_id'), 'group', ['location_id'], unique=False)
    op.create_index(op.f('ix_group_ticket_id'), 'group', ['ticket_id'], unique=False)
    op.create_table('group_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_attendance_status', oh_queue.models.db.String(length=255), nullable=False),
    sa.Column('course', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_attendance_course'), 'group_attendance', ['course'], unique=False)
    op.create_index(op.f('ix_group_attendance_group_id'), 'group_attendance', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_attendance_user_id'), 'group_attendance', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # Get alembic DB bind
    connection = op.get_bind()
    session = orm.Session(bind=connection)

    for course in session.query(ConfigEntry.course).distinct():
        session.add(ConfigEntry(key='party_enabled', value='false', public=True, course=course[0]))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_attendance_user_id'), table_name='group_attendance')
    op.drop_index(op.f('ix_group_attendance_group_id'), table_name='group_attendance')
    op.drop_index(op.f('ix_group_attendance_course'), table_name='group_attendance')
    op.drop_table('group_attendance')
    op.drop_index(op.f('ix_group_ticket_id'), table_name='group')
    op.drop_index(op.f('ix_group_location_id'), table_name='group')
    op.drop_index(op.f('ix_group_created'), table_name='group')
    op.drop_index(op.f('ix_group_course'), table_name='group')
    op.drop_index(op.f('ix_group_assignment_id'), table_name='group')
    op.drop_table('group')
    # ### end Alembic commands ###
