"""added online entries

Revision ID: 7a9d9550b30f
Revises: ee50ab5f3371
Create Date: 2020-03-08 21:58:32.016397

"""

# revision identifiers, used by Alembic.
from sqlalchemy import orm

revision = '7a9d9550b30f'
down_revision = 'ee50ab5f3371'

from alembic import op
import sqlalchemy as sa
import oh_queue.models
from oh_queue.models import *


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('call_url', sa.String(length=255), nullable=True))
    op.add_column('ticket', sa.Column('doc_url', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('call_url', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('doc_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###

    # Get alembic DB bind
    connection = op.get_bind()
    session = orm.Session(bind=connection)

    for course in session.query(ConfigEntry.course).distinct():
        session.add(ConfigEntry(key='online_active', value='false', public=True, course=course[0]))
        session.add(ConfigEntry(key='students_set_online_link', value='false', public=True, course=course[0]))
        session.add(ConfigEntry(key='students_set_online_doc', value='false', public=True, course=course[0]))

    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'doc_url')
    op.drop_column('ticket', 'call_url')
    op.drop_column('user', 'doc_url')
    op.drop_column('user', 'call_url')

    # ### end Alembic commands ###
