"""Multiple user roles

Revision ID: 826d994e7e11
Revises: None
Create Date: 2016-10-26 14:55:36.981449

"""

# revision identifiers, used by Alembic.
revision = '826d994e7e11'
down_revision = None

from alembic import op
import sqlalchemy as sa
from oh_queue.models import *
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', EnumType(Role), default=Role.student, nullable=False))
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.drop_column('user', 'is_staff')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_staff', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_column('user', 'role')
    ### end Alembic commands ###
