"""add fields to handle group signups

Revision ID: 8693ab5386b8
Revises: e80617a584e0
Create Date: 2020-06-22 01:06:37.805021

"""

# revision identifiers, used by Alembic.
revision = '8693ab5386b8'
down_revision = 'e80617a584e0'

from alembic import op
import sqlalchemy as sa
import oh_queue.models
from oh_queue.models import *


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('require_groups', sa.Boolean(), nullable=False))
    op.add_column('appointment_signup', sa.Column('group_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment_signup', 'group_name')
    op.drop_column('appointment', 'require_groups')
    # ### end Alembic commands ###
