"""added pranked column

Revision ID: 9cda112b3629
Revises: 1f54dee7ae76
Create Date: 2020-04-01 09:52:50.121056

"""

# revision identifiers, used by Alembic.
revision = '9cda112b3629'
down_revision = '1f54dee7ae76'

from alembic import op
import sqlalchemy as sa
import oh_queue.models
from oh_queue.models import *


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pranked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'pranked')
    # ### end Alembic commands ###
