"""index by course

Revision ID: c2f835ce68a7
Revises: 3ac7f97f07e4
Create Date: 2020-03-11 12:53:56.472366

"""

# revision identifiers, used by Alembic.
revision = 'c2f835ce68a7'
down_revision = '3ac7f97f07e4'

from alembic import op
import sqlalchemy as sa
import oh_queue.models
from oh_queue.models import *


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_appointment_course'), 'appointment', ['course'], unique=False)
    op.create_index(op.f('ix_appointment_signup_course'), 'appointment_signup', ['course'], unique=False)
    op.create_index(op.f('ix_assignment_course'), 'assignment', ['course'], unique=False)
    op.create_index(op.f('ix_config_entries_course'), 'config_entries', ['course'], unique=False)
    op.create_index(op.f('ix_location_course'), 'location', ['course'], unique=False)
    op.create_index(op.f('ix_ticket_course'), 'ticket', ['course'], unique=False)
    op.create_index(op.f('ix_ticket_event_course'), 'ticket_event', ['course'], unique=False)
    op.create_index(op.f('ix_user_course'), 'user', ['course'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_course'), table_name='user')
    op.drop_index(op.f('ix_ticket_event_course'), table_name='ticket_event')
    op.drop_index(op.f('ix_ticket_course'), table_name='ticket')
    op.drop_index(op.f('ix_location_course'), table_name='location')
    op.drop_index(op.f('ix_config_entries_course'), table_name='config_entries')
    op.drop_index(op.f('ix_assignment_course'), table_name='assignment')
    op.drop_index(op.f('ix_appointment_signup_course'), table_name='appointment_signup')
    op.drop_index(op.f('ix_appointment_course'), table_name='appointment')
    # ### end Alembic commands ###
