"""add signups tables

Revision ID: de36c78db106
Revises: 07e35513124b
Create Date: 2020-03-03 22:10:18.982541

"""

# revision identifiers, used by Alembic.
revision = 'de36c78db106'
down_revision = '07e35513124b'

from alembic import op
import sqlalchemy as sa
import oh_queue.models
from oh_queue.models import *


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Interval(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('helper_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['helper_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_helper_id'), 'appointment', ['helper_id'], unique=False)
    op.create_index(op.f('ix_appointment_location_id'), 'appointment', ['location_id'], unique=False)
    op.create_index(op.f('ix_appointment_start_time'), 'appointment', ['start_time'], unique=False)
    op.create_table('appointment_signup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_signup_appointment_id'), 'appointment_signup', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_appointment_signup_user_id'), 'appointment_signup', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointment_signup_user_id'), table_name='appointment_signup')
    op.drop_index(op.f('ix_appointment_signup_appointment_id'), table_name='appointment_signup')
    op.drop_table('appointment_signup')
    op.drop_index(op.f('ix_appointment_start_time'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_location_id'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_helper_id'), table_name='appointment')
    op.drop_table('appointment')
    # ### end Alembic commands ###
