"""Added fields for juggling

Revision ID: e330a9be55f8
Revises: e4b5bd2a05cc
Create Date: 2020-02-23 06:10:28.465718

"""

# revision identifiers, used by Alembic.
from sqlalchemy import orm

revision = 'e330a9be55f8'
down_revision = 'e4b5bd2a05cc'

from alembic import op
import sqlalchemy as sa
import oh_queue.models
from oh_queue.models import *


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('hold_time', sa.DateTime(), nullable=True))
    op.add_column('ticket', sa.Column('rerequest_threshold', sa.DateTime(), nullable=True))
    op.add_column('ticket', sa.Column('rerequest_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'rerequest_time')
    op.drop_column('ticket', 'rerequest_threshold')
    op.drop_column('ticket', 'hold_time')

    # ### end Alembic commands ###
