"""added slack config options

Revision ID: e80617a584e0
Revises: c568f4d277de
Create Date: 2020-04-09 15:03:43.071903

"""

# revision identifiers, used by Alembic.
from sqlalchemy import orm

revision = 'e80617a584e0'
down_revision = 'c568f4d277de'

from alembic import op
import sqlalchemy as sa
import oh_queue.models
from oh_queue.models import *


def upgrade():
    # Get alembic DB bind
    connection = op.get_bind()
    session = orm.Session(bind=connection)

    for course in session.query(ConfigEntry.course).distinct():
        session.add(ConfigEntry(key='slack_notif_long_queue', value='false', public=True, course=course[0]))
        session.add(ConfigEntry(key='slack_notif_appt_summary', value='false', public=True, course=course[0]))
        session.add(ConfigEntry(key='slack_notif_missed_appt', value='false', public=True, course=course[0]))

    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
