"""Add online options to locations

Revision ID: e96dc20c344a
Revises: 4c81c3744bc4
Create Date: 2020-08-28 03:23:57.419222

"""

# revision identifiers, used by Alembic.
revision = 'e96dc20c344a'
down_revision = '4c81c3744bc4'

from alembic import op
import sqlalchemy as sa
import oh_queue.models
from oh_queue.models import *


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('link', sa.String(length=255), nullable=False))
    op.add_column('location', sa.Column('online', sa.Boolean(), nullable=False, server_default=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'online')
    op.drop_column('location', 'link')
    # ### end Alembic commands ###
