"""added appointments tables

Revision ID: ee50ab5f3371
Revises: 7857a34ef101
Create Date: 2020-03-08 20:15:02.275445

"""

# revision identifiers, used by Alembic.
from sqlalchemy import orm

revision = 'ee50ab5f3371'
down_revision = '7857a34ef101'

from alembic import op
import sqlalchemy as sa
import oh_queue.models
from oh_queue.models import *


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Interval(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('helper_id', sa.Integer(), nullable=True),
    sa.Column('status', oh_queue.models.db.String(length=255), nullable=False),
    sa.Column('course', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['helper_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_helper_id'), 'appointment', ['helper_id'], unique=False)
    op.create_index(op.f('ix_appointment_location_id'), 'appointment', ['location_id'], unique=False)
    op.create_index(op.f('ix_appointment_start_time'), 'appointment', ['start_time'], unique=False)
    op.create_index(op.f('ix_appointment_status'), 'appointment', ['status'], unique=False)
    op.create_table('appointment_signup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('attendance_status', oh_queue.models.db.String(length=255), nullable=False),
    sa.Column('course', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_signup_appointment_id'), 'appointment_signup', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_appointment_signup_assignment_id'), 'appointment_signup', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_appointment_signup_user_id'), 'appointment_signup', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # Get alembic DB bind
    connection = op.get_bind()
    session = orm.Session(bind=connection)

    for course in session.query(ConfigEntry.course).distinct():
        session.add(ConfigEntry(key='online_active', value='false', public=True, course=course[0]))

    session.commit()



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointment_signup_user_id'), table_name='appointment_signup')
    op.drop_index(op.f('ix_appointment_signup_assignment_id'), table_name='appointment_signup')
    op.drop_index(op.f('ix_appointment_signup_appointment_id'), table_name='appointment_signup')
    op.drop_table('appointment_signup')
    op.drop_index(op.f('ix_appointment_status'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_start_time'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_location_id'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_helper_id'), table_name='appointment')
    op.drop_table('appointment')
    # ### end Alembic commands ###
